services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - grao-network

  graoestoque:
    build:
      context: .
      dockerfile: ./cmd/GraoEstoque/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DSN: ${POSTGRES_DSN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      PER_TENANT_MIGRATION_PATH: ${PER_TENANT_MIGRATION_PATH}
    networks:
      - grao-network
    volumes:
      - grao_log:/app/logs

networks:
  grao-network:
    driver: bridge

volumes:
  db_data:
  grao_log:
